spring:
  application:
    name: loyalty-pro-backend
  datasource:
    url: "jdbc:mysql://localhost:3306/loyalty-pro"
    username: "root"
    password: "root"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: "update"
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  error:
    include-message: always